#include "COMPETITEUR.h"
#include "PARTICIPATION.h"
#include "COURSE.h"
#include "COURSE_SLALOM.h"
#include <iostream>

int main()
{
	COMPETITEUR * A = new COMPETITEUR(1, "Perrine", "Pellen", 60, 12);
	COMPETITEUR * B = new COMPETITEUR(2, "Ingemar", "Stenmark", 120, 13);
	COMPETITEUR * C = new COMPETITEUR(3, "Ingrid", "Jacquemod", 30, 15);
	COMPETITEUR * D = new COMPETITEUR(4, "Alberto", "Tomba", 28, 16);
	COMPETITEUR * E = new COMPETITEUR(5, "Mickaël", "Von Grünen", 1, 7);
	COMPETITEUR * F = new COMPETITEUR(6, "Bode", "Miller", 3, 10);
	COMPETITEUR * G = new COMPETITEUR(7, "Jean-Baptiste", "Grange", 6, 23);
	COMPETITEUR * H = new COMPETITEUR(8, "Marcel", "Hirscher", 12, 13);
	COMPETITEUR * I = new COMPETITEUR(9, "Lindsey", "Vonn", 3, 6);
	COMPETITEUR * J = new COMPETITEUR(10, "Marta", "Bassino", 61, 12);
	COMPETITEUR * K = new COMPETITEUR(11, "Carole", "Merle", 12, 13);
	COMPETITEUR * L = new COMPETITEUR(12, "Tessa", "Vorley", 3, 5);
	COMPETITEUR * M = new COMPETITEUR(13, "Mickaela", "Shiffrin", 6, 22);
	COMPETITEUR * N = new COMPETITEUR(14, "Tina", "Maze", 23, 33);
	COMPETITEUR * O = new COMPETITEUR(15, "Erika", "Hess", 31, 45);
	COMPETITEUR * P = new COMPETITEUR(16, "*Marielle", "*Goitschel", 22, 2);
	COMPETITEUR * Q = new COMPETITEUR(17, "*Clément", "*Noël", 33, 3);
	COMPETITEUR * R = new COMPETITEUR(18, "*Anemone", "*Marmottand", 44, 4);
	COMPETITEUR * S = new COMPETITEUR(19, "*Anemone", "*Marmottand", 19, 0);
	COMPETITEUR * T = new COMPETITEUR(20, "*Anemone", "*Marmottand", 20, 0);
	COMPETITEUR * U = new COMPETITEUR(21, "*Anemone", "*Marmottand", 43, 0);
	COMPETITEUR * V = new COMPETITEUR(22, "*Anemone", "*Marmottand", 42, 0);
	COMPETITEUR * W = new COMPETITEUR(23, "*Anemone", "*Marmottand", 41, 0);
	COMPETITEUR * X = new COMPETITEUR(24, "*Anemone", "*Marmottand", 40, 0);
	COMPETITEUR * Y = new COMPETITEUR(25, "*Anemone", "*Marmottand", 39, 0);
	COMPETITEUR * Z = new COMPETITEUR(26, "*Anemone", "*Marmottand", 35, 0);
	COMPETITEUR * AA = new COMPETITEUR(27, "*Anemone", "*Marmottand", 23, 0);
	COMPETITEUR * BB = new COMPETITEUR(28, "*Anemone", "*Marmottand", 10, 0);
	COMPETITEUR * CC = new COMPETITEUR(29, "*Anemone", "*Marmottand", 9, 0);
	COMPETITEUR * DD = new COMPETITEUR(30, "*Last", "*1", 44, 0);
	COMPETITEUR * EE = new COMPETITEUR(31, "*Last", "*2", 12, 0);
	COMPETITEUR * FF = new COMPETITEUR(32, "*Last", "*3", 11, 0);
	COMPETITEUR * GG = new COMPETITEUR(33, "*Last", "*4", 10, 0);
	COMPETITEUR * HH = new COMPETITEUR(34, "*Last", "*5", 9, 0);
	COMPETITEUR * II = new COMPETITEUR(35, "*Last", "*6", 8, 0);
	COMPETITEUR * JJ = new COMPETITEUR(36, "*Last", "*7", 7, 0);
	COMPETITEUR * KK = new COMPETITEUR(37, "*Last", "*8", 6, 0);
	COMPETITEUR * LL = new COMPETITEUR(38, "*Last", "*9", 5, 0);
	COMPETITEUR * MM = new COMPETITEUR(39, "*Last", "*10", 4, 0);
	COMPETITEUR * NN = new COMPETITEUR(40, "*Last", "*11", 3, 0);
	COMPETITEUR * OO = new COMPETITEUR(41, "*Last", "*12", 2, 0);
	COMPETITEUR * PP = new COMPETITEUR(42, "*Last", "*13", 1, 0);
	COMPETITEUR * QQ = new COMPETITEUR(43, "*Last", "*14", 0, 0);
	COMPETITEUR * RR = new COMPETITEUR(44, "*Last", "*15", 0, 0);
	COMPETITEUR * SS = new COMPETITEUR(45, "*Last", "*16", 0, 0);
	COMPETITEUR * TT = new COMPETITEUR(46, "*Last", "*17", 0, 0);
	COMPETITEUR * UU = new COMPETITEUR(47, "*Last", "*18", 0, 0);
	COMPETITEUR * VV = new COMPETITEUR(48, "*Last", "*19", 0, 0);
	COMPETITEUR * WW = new COMPETITEUR(49, "*Last", "*20", 0, 0);
	COMPETITEUR * XX = new COMPETITEUR(50, "*Last", "*21", 0, 0);
	COMPETITEUR * YY = new COMPETITEUR(51, "*Last", "*22", 0, 0);
	COMPETITEUR * ZZ = new COMPETITEUR(52, "*Last", "*23", 0, 0);
	COMPETITEUR * AAA = new COMPETITEUR(53, "*Last", "*24", 0, 0);
	COMPETITEUR * BBB = new COMPETITEUR(54, "*Last", "*25", 0, 0);
	COMPETITEUR * CCC = new COMPETITEUR(55, "*Last", "*26", 0, 0);
	COMPETITEUR * DDD = new COMPETITEUR(56, "*Last", "*27", 0, 0);
	COMPETITEUR * EEE = new COMPETITEUR(57, "*Last", "*28", 0, 0);
	COMPETITEUR * FFF = new COMPETITEUR(58, "*Last", "*29", 0, 0);
	COMPETITEUR * GGG = new COMPETITEUR(59, "*Last", "*30", 0, 0);
	COMPETITEUR * HHH = new COMPETITEUR(60, "*Last", "*31", 0, 0);
	COMPETITEUR * III = new COMPETITEUR(61, "*Last", "*32", 0, 0);
	COMPETITEUR * JJJ = new COMPETITEUR(62, "*Last", "*33", 0, 0);
	COMPETITEUR * KKK = new COMPETITEUR(63, "*Last", "*34", 0, 0);
	COMPETITEUR * LLL = new COMPETITEUR(64, "*Last", "*35", 0, 0);
	COMPETITEUR * MMM = new COMPETITEUR(65, "*Last", "*36", 0, 0);
	COMPETITEUR * NNN = new COMPETITEUR(66, "*Last", "*37", 0, 0);
	COMPETITEUR * OOO = new COMPETITEUR(67, "*Last", "*38", 0, 0);
	COMPETITEUR * PPP = new COMPETITEUR(68, "*Last", "*39", 0, 0);
	COMPETITEUR * QQQ = new COMPETITEUR(69, "*Last", "*40", 0, 0);
	COMPETITEUR * RRR = new COMPETITEUR(70, "*Last", "*41", 0, 0);
	COMPETITEUR * SSS = new COMPETITEUR(71, "*Last", "*42", 0, 0);
	COMPETITEUR * TTT = new COMPETITEUR(72, "*Last", "*43", 0, 0);
	COMPETITEUR * UUU = new COMPETITEUR(73, "*Last", "*44", 0, 0);
	COMPETITEUR * VVV = new COMPETITEUR(74, "*Last", "*45", 0, 0);
	COMPETITEUR * WWW = new COMPETITEUR(75, "*Last", "*46", 0, 0);
	COMPETITEUR * XXX = new COMPETITEUR(76, "*Last", "*47", 0, 0);
	COMPETITEUR * YYY = new COMPETITEUR(77, "*Last", "*48", 0, 0);
	COMPETITEUR * ZZZ = new COMPETITEUR(78, "*Last", "*49", 0, 0);
	COMPETITEUR * AAAA = new COMPETITEUR(79, "*Last", "*50", 0, 0);
	COMPETITEUR * BBBB = new COMPETITEUR(80, "*Last", "*51", 0, 0);
	COMPETITEUR * CCCC = new COMPETITEUR(81, "*Last", "*52", 0, 0);
	COMPETITEUR * DDDD = new COMPETITEUR(82, "*Last", "*53", 0, 0);
	COMPETITEUR * EEEE = new COMPETITEUR(83, "*Last", "*54", 0, 0);
	COMPETITEUR * FFFF = new COMPETITEUR(84, "*Last", "*55", 0, 0);
	COMPETITEUR * GGGG = new COMPETITEUR(85, "*Last", "*56", 0, 0);
	COMPETITEUR * HHHH = new COMPETITEUR(86, "*Last", "*57", 0, 0);
	COMPETITEUR * IIII = new COMPETITEUR(87, "*Last", "*58", 0, 0);
	COMPETITEUR * JJJJ = new COMPETITEUR(88, "*Last", "*59", 0, 0);
	COMPETITEUR * KKKK = new COMPETITEUR(89, "*Last", "*60", 0, 0);
	COMPETITEUR * LLLL = new COMPETITEUR(90, "*Last", "*61", 0, 0);
	COMPETITEUR * MMMM = new COMPETITEUR(91, "*Last", "*62", 0, 0);
	COMPETITEUR * NNNN = new COMPETITEUR(92, "*Last", "*63", 0, 0);
	COMPETITEUR * OOOO = new COMPETITEUR(93, "*Last", "*64", 0, 0);
	COMPETITEUR * PPPP = new COMPETITEUR(94, "*Last", "*65", 0, 0);
	COMPETITEUR * QQQQ = new COMPETITEUR(95, "*Last", "*66", 0, 0);
	COMPETITEUR * RRRR = new COMPETITEUR(96, "*Last", "*67", 0, 0);
	COMPETITEUR * SSSS = new COMPETITEUR(97, "*Last", "*68", 0, 0);
	COMPETITEUR * TTTT = new COMPETITEUR(98, "*Last", "*69", 0, 0);
	COMPETITEUR * UUUU = new COMPETITEUR(99, "*Last", "*70", 0, 0);
	COMPETITEUR * VVVV = new COMPETITEUR(100, "*Last", "*71", 0, 0);

	
	PARTICIPATION * lesParticipants = new PARTICIPATION[100];

	PARTICIPATION P1(A);
	lesParticipants[0] = P1;
	PARTICIPATION P2(B);
	lesParticipants[1] = P2;
	PARTICIPATION P3(C);
	lesParticipants[2] = P3;
	PARTICIPATION P4(D);
	lesParticipants[3] = P4;
	PARTICIPATION P5(E);
	lesParticipants[4] = P5;
	PARTICIPATION P6(F);
	lesParticipants[5] = P6;
	PARTICIPATION P7(G);
	lesParticipants[6] = P7;
	PARTICIPATION P8(H);
	lesParticipants[7] = P8;
	PARTICIPATION P9(I);
	lesParticipants[8] = P9;
	PARTICIPATION P10(J);
	lesParticipants[9] = P10;
	PARTICIPATION P11(K);
	lesParticipants[10] = P11;
	PARTICIPATION P12(L);
	lesParticipants[11] = P12;
	PARTICIPATION P13(M);
	lesParticipants[12] = P13;
	PARTICIPATION P14(N);
	lesParticipants[13] = P14;
	PARTICIPATION P15(O);
	lesParticipants[14] = P15;
	PARTICIPATION P16(P);
	lesParticipants[15] = P16;
	PARTICIPATION P17(Q);
	lesParticipants[16] = P17;
	PARTICIPATION P18(R);
	lesParticipants[17] = P18;
	PARTICIPATION P19(S);
	lesParticipants[18] = P19;
	PARTICIPATION P20(T);
	lesParticipants[19] = P20;
	PARTICIPATION P21(U);
	lesParticipants[20] = P21;
	PARTICIPATION P22(V);
	lesParticipants[21] = P22;
	PARTICIPATION P23(W);
	lesParticipants[22] = P23;
	PARTICIPATION P24(X);
	lesParticipants[23] = P24;
	PARTICIPATION P25(Y);
	lesParticipants[24] = P25;
	PARTICIPATION P26(Z);
	lesParticipants[25] = P26;
	PARTICIPATION P27(AA);
	lesParticipants[26] = P27;
	PARTICIPATION P28(BB);
	lesParticipants[27] = P28;
	PARTICIPATION P29(CC);
	lesParticipants[28] = P29;
	PARTICIPATION P30(DD);
	lesParticipants[29] = P30;
	PARTICIPATION P31(EE);
	lesParticipants[30] = P31;
	PARTICIPATION P32(FF);
	lesParticipants[31] = P32;
	PARTICIPATION P33(GG);
	lesParticipants[32] = P33;
	PARTICIPATION P34(HH);
	lesParticipants[33] = P34;
	PARTICIPATION P35(II);
	lesParticipants[34] = P35;
	PARTICIPATION P36(JJ);
	lesParticipants[35] = P36;
	PARTICIPATION P37(KK);
	lesParticipants[36] = P37;
	PARTICIPATION P38(LL);
	lesParticipants[37] = P38;
	PARTICIPATION P39(MM);
	lesParticipants[38] = P39;
	PARTICIPATION P40(NN);
	lesParticipants[39] = P40;
	PARTICIPATION P41(OO);
	lesParticipants[40] = P41;
	PARTICIPATION P42(PP);
	lesParticipants[41] = P42;
	PARTICIPATION P43(QQ);
	lesParticipants[42] = P43;
	PARTICIPATION P44(RR);
	lesParticipants[43] = P44;
	PARTICIPATION P45(SS);
	lesParticipants[44] = P45;
	PARTICIPATION P46(TT);
	lesParticipants[45] = P46;
	PARTICIPATION P47(UU);
	lesParticipants[46] = P47;
	PARTICIPATION P48(VV);
	lesParticipants[47] = P48;
	PARTICIPATION P49(WW);
	lesParticipants[48] = P49;
	PARTICIPATION P50(XX);
	lesParticipants[49] = P50;
	PARTICIPATION P51(YY);
	lesParticipants[50] = P51;
	PARTICIPATION P52(ZZ);
	lesParticipants[51] = P52;
	PARTICIPATION P53(AAA);
	lesParticipants[52] = P53;
	PARTICIPATION P54(BBB);
	lesParticipants[53] = P54;
	PARTICIPATION P55(CCC);
	lesParticipants[54] = P55;
	PARTICIPATION P56(DDD);
	lesParticipants[55] = P56;
	PARTICIPATION P57(EEE);
	lesParticipants[56] = P57;
	PARTICIPATION P58(FFF);
	lesParticipants[57] = P58;
	PARTICIPATION P59(GGG);
	lesParticipants[58] = P59;
	PARTICIPATION P60(HHH);
	lesParticipants[59] = P60;
	PARTICIPATION P61(III);
	lesParticipants[60] = P61;
	PARTICIPATION P62(JJJ);
	lesParticipants[61] = P62;
	PARTICIPATION P63(KKK);
	lesParticipants[62] = P63;
	PARTICIPATION P64(LLL);
	lesParticipants[63] = P64;
	PARTICIPATION P65(MMM);
	lesParticipants[64] = P65;
	PARTICIPATION P66(NNN);
	lesParticipants[65] = P66;
	PARTICIPATION P67(OOO);
	lesParticipants[66] = P67;
	PARTICIPATION P68(PPP);
	lesParticipants[67] = P68;
	PARTICIPATION P69(QQQ);
	lesParticipants[68] = P69;
	PARTICIPATION P70(RRR);
	lesParticipants[69] = P70;
	PARTICIPATION P71(SSS);
	lesParticipants[70] = P71;
	PARTICIPATION P72(TTT);
	lesParticipants[71] = P72;
	PARTICIPATION P73(UUU);
	lesParticipants[72] = P73;
	PARTICIPATION P74(VVV);
	lesParticipants[73] = P74;
	PARTICIPATION P75(WWW);
	lesParticipants[74] = P75;
	PARTICIPATION P76(XXX);
	lesParticipants[75] = P76;
	PARTICIPATION P77(YYY);
	lesParticipants[76] = P77;
	PARTICIPATION P78(ZZZ);
	lesParticipants[77] = P78;
	PARTICIPATION P79(AAAA);
	lesParticipants[78] = P79;
	PARTICIPATION P80(BBBB);
	lesParticipants[79] = P80;
	PARTICIPATION P81(CCCC);
	lesParticipants[80] = P81;
	PARTICIPATION P82(DDDD);
	lesParticipants[81] = P82;
	PARTICIPATION P83(EEEE);
	lesParticipants[82] = P83;
	PARTICIPATION P84(FFFF);
	lesParticipants[83] = P84;
	PARTICIPATION P85(GGGG);
	lesParticipants[84] = P85;
	PARTICIPATION P86(HHHH);
	lesParticipants[85] = P86;
	PARTICIPATION P87(IIII);
	lesParticipants[86] = P87;
	PARTICIPATION P88(JJJJ);
	lesParticipants[87] = P88;
	PARTICIPATION P89(KKKK);
	lesParticipants[88] = P89;
	PARTICIPATION P90(LLLL);
	lesParticipants[89] = P90;
	PARTICIPATION P91(MMMM);
	lesParticipants[90] = P91;
	PARTICIPATION P92(NNNN);
	lesParticipants[91] = P92;
	PARTICIPATION P93(OOOO);
	lesParticipants[92] = P93;
	PARTICIPATION P94(PPPP);
	lesParticipants[93] = P94;
	PARTICIPATION P95(QQQQ);
	lesParticipants[94] = P95;
	PARTICIPATION P96(RRRR);
	lesParticipants[95] = P96;
	PARTICIPATION P97(SSSS);
	lesParticipants[96] = P97;
	PARTICIPATION P98(TTTT);
	lesParticipants[97] = P98;
	PARTICIPATION P99(UUUU);
	lesParticipants[98] = P99;
	PARTICIPATION P100(VVVV);
	lesParticipants[99] = P100;

	COURSE_SLALOM Slalom("Kitzbühel", "20/01/2025", lesParticipants);

	Slalom.afficherLesParticipations();
	std::cout << "-------------------------------------------- \n";
	Slalom.traitementDossards();
	Slalom.afficherLesParticipations();
}